### PR TITLE
Admas Fall Portal

### PR DESCRIPTION
**Pull request by Valdifer**
Added Admas Fall portal

### CODE REVIEW

**Comment by FrozenKiller35** [comment]
Are you sure about the Quest's ? Because we have a parser for those stuff and if its not in quest_data it is removed from NC / GF or maybe set to a level 99 quest and they are not usable :O :O :O

**Comment by Valdifer** [comment]
> Are you sure about the Quest's ? Because we have a parser for those stuff and if its not in quest_data it is removed from NC / GF or maybe set to a level 99 quest and they are not usable :O :O :O

Nop, i'm not sure sorry, i was just getting a warn all the time about those quests and i fixed it adding to XML but i don't know those quests exactly. Just copied from here:

http://aiondatabase.net/us/quest/15565/

**Comment by FrozenKiller35** [comment]
what did the warning say exactly?

**Comment by Valdifer** [comment]
> what did the warning say exactly?

In the quest.log

2019-04-29 11:13:42,331 [QuestService] Can't find Quest: 15565 in quest_data.xml

and too for 25565

**Comment by FrozenKiller35** [comment]
Delete AL-Game-5.8\data\scripts\system\handlers\quest\esterra\_15565DefenceofArielsRefuge.java and AL-Game-5.8\data\scripts\system\handlers\quest\nosra\_25565DefendAzphelsTemple.java and the warn is gone ;)

**Comment by Valdifer** [comment]
Closing and redoing it again, sry i had not time D:

**Pull request closed without merging**
